model_name : google/vit-base-patch16-224-in21k
device : cuda
dataset_path : ./dataset
trainer:
  output_dir: vit_food_model
  learning_rate: 5e-5
  per_device_train_batch_size: 16
  gradient_accumulation_steps: 4
  per_device_eval_batch_size: 16
  num_train_epochs: 3
  warmup_ratio: 0.1
  logging_steps: 10
  metric_for_best_model: accuracy

